# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppointmentManagementDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QTableView

import images.HMS
from About import Ui_AboutWindow
from pymongo import MongoClient


class AlignDelegate(QtWidgets.QStyledItemDelegate):
    def initStyleOption(self, option, index):
        super(AlignDelegate, self).initStyleOption(option, index)
        option.displayAlignment = QtCore.Qt.AlignCenter
        
class Ui_AppointmentManagementDatabase(object):
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def ShowDatabase(self):
        client = MongoClient('localhost:27017')
        db = client.HSMD
        col = db.Appointment_DB
        print("database connected")

        datas = list(col.find({},{"_id": 0,"DOCTOR ID": 1,"DOCTOR NAME": 1,"SPECIALIZATION": 1,"WORKING DAYS": 1,"WORKING HOURS": 1,"1ST PATIENT NAME": 1,"2ND PATIENT NAME": 1,"3RD PATIENT NAME": 1}))
        self.tableWidget.setRowCount(21)
        delegate = AlignDelegate(self.tableWidget)
        self.tableWidget.setItemDelegate(delegate)

        # print pada tabel
        keys = datas[0].keys()
        for index, key in enumerate(keys):
            # print(type(key), key)
            self.tableWidget.setItem(
                0, index, QtWidgets.QTableWidgetItem(key))

        # print data dke tabel
        for row_index, data in enumerate(datas):
            for col_index, key in enumerate(data.keys()):
                # tambah 1 karena tambah pala
                self.tableWidget.setItem(
                    row_index , col_index,  QtWidgets.QTableWidgetItem(str(data[key])))


    def setupUi(self, AppointmentManagementDatabase):
        AppointmentManagementDatabase.setObjectName("AppointmentManagementDatabase")
        AppointmentManagementDatabase.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AppointmentManagementDatabase.setWindowIcon(icon)
        AppointmentManagementDatabase.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(AppointmentManagementDatabase)
        self.centralwidget.setObjectName("centralwidget")

        self.AMDB_back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.AMDB_back_btn.setGeometry(QtCore.QRect(1400, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AMDB_back_btn.setFont(font)
        self.AMDB_back_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(58, 68, 255);\n"
"border-radius: 20px;")
        self.AMDB_back_btn.clicked.connect(AppointmentManagementDatabase.close)
        self.AMDB_back_btn.setObjectName("AMDB_back_btn")

        self.AMDB_LD_btn = QtWidgets.QPushButton(self.centralwidget)
        self.AMDB_LD_btn.setGeometry(QtCore.QRect(1010, 760, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AMDB_LD_btn.setFont(font)
        self.AMDB_LD_btn.setStyleSheet("color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(112, 161, 255,1.0), stop:1 rgba(55, 66, 250,1.0));\n"
"    border-radius: 20px;")
        self.AMDB_LD_btn.clicked.connect(self.ShowDatabase)
        self.AMDB_LD_btn.setObjectName("AMDB_LD_btn")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 140, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: rgb(58, 134, 255);\n"
"    background-color: white;\n"
"    border: 2px solid rgb(58, 134, 255);\n"
"    border-radius: 20px;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 81, 81))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"image: url(:/newPrefix4/icon.png);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

# tableWideget-----------------------------------------------------------------
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(600, 150, 971, 571))
        self.tableWidget.setStyleSheet("selection-background-color: qlineargradient(x1: 0, y1: 0, x2: 0.5, y2: 0.5,\n"
"                                stop: 0 #25CCF7, stop: 1 #1B9CFC);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setObjectName("tableWidget")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(180)
        self.tableWidget.verticalHeader().setDefaultSectionSize(38)
#-----------------------------------------------------------------------------
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 551, 771))
        self.label_3.setStyleSheet("image: url(:/newPrefix5/database4.png);\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.tableWidget.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.AMDB_back_btn.raise_()
        self.AMDB_LD_btn.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        AppointmentManagementDatabase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AppointmentManagementDatabase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        AppointmentManagementDatabase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AppointmentManagementDatabase)
        self.statusbar.setObjectName("statusbar")
        AppointmentManagementDatabase.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(AppointmentManagementDatabase)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(AppointmentManagementDatabase)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOption.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(AppointmentManagementDatabase)
        QtCore.QMetaObject.connectSlotsByName(AppointmentManagementDatabase)

        self.actionExit.triggered.connect(AppointmentManagementDatabase.close)
        self.actionAbout.triggered.connect(self.openAbout)

    def retranslateUi(self, AppointmentManagementDatabase):
        _translate = QtCore.QCoreApplication.translate
        AppointmentManagementDatabase.setWindowTitle(_translate("AppointmentManagementDatabase", "HMS - Appointment Management Database"))
        self.AMDB_back_btn.setText(_translate("AppointmentManagementDatabase", "Back"))
        self.AMDB_LD_btn.setText(_translate("AppointmentManagementDatabase", "Load Data"))
        self.label.setText(_translate("AppointmentManagementDatabase", "                   Appointment Management Database"))
        self.label_4.setText(_translate("AppointmentManagementDatabase", "Appointments Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AppointmentManagementDatabase", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AppointmentManagementDatabase", "Doctor Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AppointmentManagementDatabase", "Specialization"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("AppointmentManagementDatabase", "Working Days"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("AppointmentManagementDatabase", "Working Hours"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("AppointmentManagementDatabase", "1st Patient Name"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("AppointmentManagementDatabase", "2nd Patient Name"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("AppointmentManagementDatabase", "3rd Patient Name"))
        self.menuOption.setTitle(_translate("AppointmentManagementDatabase", "Option"))
        self.menuHelp.setTitle(_translate("AppointmentManagementDatabase", "Help"))
        self.actionExit.setText(_translate("AppointmentManagementDatabase", "Exit"))
        self.actionAbout.setText(_translate("AppointmentManagementDatabase", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AppointmentManagementDatabase = QtWidgets.QMainWindow()
    ui = Ui_AppointmentManagementDatabase()
    ui.setupUi(AppointmentManagementDatabase)
    AppointmentManagementDatabase.show()
    sys.exit(app.exec_())
