# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DoctorView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import images.HMS
from PyQt5.QtWidgets import QMessageBox
from covid19 import Ui_CovidWindow
from About import Ui_AboutWindow
from StockOfGoodsDatabase import Ui_StockOfGoodsDatabase
from AppointmentManagementDatabase import Ui_AppointmentManagementDatabase


class Ui_DoctorView(object):
    def openCovid(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CovidWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openStockOfGoodsDatabase(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_StockOfGoodsDatabase()
        self.ui.setupUi(self.window)
        self.window.show()

    def openAppointmentManagementDatabase(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AppointmentManagementDatabase()
        self.ui.setupUi(self.window)
        self.window.show()

    def logout(self):
        msg = QMessageBox()
        msg.setWindowTitle("Message")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        msg.setWindowIcon(icon)
        msg.setIcon(QMessageBox.Information)
        font = QtGui.QFont()
        font.setPointSize(10)
        msg.setFont(font)
        msg.setText("Doctor Admin Successfully Loged Out")
        msg.exec();
        
    def setupUi(self, DoctorView):
        DoctorView.setObjectName("DoctorView")
        DoctorView.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DoctorView.setWindowIcon(icon)
        DoctorView.setStyleSheet("background-color: rgb(190, 232, 254);")
        self.centralwidget = QtWidgets.QWidget(DoctorView)
        self.centralwidget.setObjectName("centralwidget")


        self.DS_logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.DS_logout_btn.setGeometry(QtCore.QRect(1420, 20, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DS_logout_btn.setFont(font)
        self.DS_logout_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(58, 68, 255);\n"
"border-radius: 20px;")
        self.DS_logout_btn.clicked.connect(DoctorView.close)
        self.DS_logout_btn.clicked.connect(self.logout)
        self.DS_logout_btn.setObjectName("DS_logout_btn")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 81, 81))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/newPrefix4/icon.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.DS_spa_btn = QtWidgets.QPushButton(self.centralwidget)
        self.DS_spa_btn.setGeometry(QtCore.QRect(1040, 160, 461, 261))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.DS_spa_btn.setFont(font)
        self.DS_spa_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.DS_spa_btn.clicked.connect(self.openAppointmentManagementDatabase)
        self.DS_spa_btn.setObjectName("DS_spa_btn")

        self.DS_hml_btn = QtWidgets.QPushButton(self.centralwidget)
        self.DS_hml_btn.setGeometry(QtCore.QRect(1040, 490, 461, 271))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.DS_hml_btn.setFont(font)
        self.DS_hml_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.DS_hml_btn.clicked.connect(self.openStockOfGoodsDatabase)
        self.DS_hml_btn.setObjectName("DS_hml_btn")

        self.DS_covid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.DS_covid_btn.setGeometry(QtCore.QRect(1520, 810, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.DS_covid_btn.setFont(font)
        self.DS_covid_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.DS_covid_btn.clicked.connect(self.openCovid)
        self.DS_covid_btn.setObjectName("DS_covid_btn")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 90, 1011, 831))
        self.label_7.setStyleSheet("image: url(:/newPrefix2/doctor.jpg);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.label.raise_()
        self.DS_logout_btn.raise_()
        self.label_2.raise_()
        self.DS_spa_btn.raise_()
        self.DS_hml_btn.raise_()
        self.DS_covid_btn.raise_()
        DoctorView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DoctorView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        DoctorView.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(DoctorView)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(DoctorView)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DoctorView)
        QtCore.QMetaObject.connectSlotsByName(DoctorView)

        self.actionAbout.triggered.connect(self.openAbout)
        self.actionExit.triggered.connect(DoctorView.close)

    def retranslateUi(self, DoctorView):
        _translate = QtCore.QCoreApplication.translate
        DoctorView.setWindowTitle(_translate("DoctorView", "HMS - Doctor View"))
        self.DS_logout_btn.setText(_translate("DoctorView", "Logout"))
        self.label.setText(_translate("DoctorView", "               Doctor Section"))
        self.DS_spa_btn.setText(_translate("DoctorView", "See Patient Appointments"))
        self.DS_hml_btn.setText(_translate("DoctorView", "Hospital Medicine List"))
        self.DS_covid_btn.setToolTip(_translate("DoctorView", "<html><head/><body><p><span style=\" font-weight:400; color:#ff0000;\">Check The Status of Covid-19</span></p></body></html>"))
        self.DS_covid_btn.setText(_translate("DoctorView", "!"))
        self.menuFile.setTitle(_translate("DoctorView", "Option"))
        self.menuHelp.setTitle(_translate("DoctorView", "Help"))
        self.actionExit.setText(_translate("DoctorView", "Exit"))
        self.actionAbout.setText(_translate("DoctorView", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DoctorView = QtWidgets.QMainWindow()
    ui = Ui_DoctorView()
    ui.setupUi(DoctorView)
    DoctorView.show()
    sys.exit(app.exec_())
