# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DoctorManagementDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QTableView
import images.HMS
from About import Ui_AboutWindow
from pymongo import MongoClient

class AlignDelegate(QtWidgets.QStyledItemDelegate):
    def initStyleOption(self, option, index):
        super(AlignDelegate, self).initStyleOption(option, index)
        option.displayAlignment = QtCore.Qt.AlignCenter

class Ui_DoctorManagementDatabase(object):
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def ShowDatabase(self):
        client = MongoClient('localhost:27017')
        db = client.HSMD
        col = db.Doctor_DB
        print("database connected")

        datas = list(col.find({},{"_id": 0,"ID": 1,"NAME": 1,"SPECIALIZATION": 1,"CONTACT": 1,"DATE & TIME": 1}))
        
        self.tableWidget.setColumnCount(5)
        delegate = AlignDelegate(self.tableWidget)
        self.tableWidget.setItemDelegate(delegate)
        

        # print pala tabel
        keys = datas[0].keys()
        for index, key in enumerate(keys):
            # print(type(key), key)
            self.tableWidget.setItem(
                0, index, QtWidgets.QTableWidgetItem(key))

        # print data dke tabel
        for row_index, data in enumerate(datas):
            for col_index, key in enumerate(data.keys()):
                # tambah 1 karena tambah pala
                self.tableWidget.setItem(
                    row_index , col_index,  QtWidgets.QTableWidgetItem(str(data[key])))
                

    def setupUi(self, DoctorManagementDatabase):
        DoctorManagementDatabase.setObjectName("DoctorManagementDatabase")
        DoctorManagementDatabase.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DoctorManagementDatabase.setWindowIcon(icon)
        DoctorManagementDatabase.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(DoctorManagementDatabase)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")


        self.DMD_back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.DMD_back_btn.setGeometry(QtCore.QRect(1420, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DMD_back_btn.setFont(font)
        self.DMD_back_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(58, 68, 255);\n"
"border-radius: 20px;")
        self.DMD_back_btn.clicked.connect(DoctorManagementDatabase.close)
        self.DMD_back_btn.setObjectName("DMD_back_btn")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 81, 81))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"image: url(:/newPrefix4/icon.png);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 551, 771))
        self.label_3.setStyleSheet("image: url(:/newPrefix5/database4.png);\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

# table Widget ------------------------------------------------------------------
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(600, 150, 971, 571))
        self.tableWidget.setStyleSheet("selection-background-color: qlineargradient(x1: 0, y1: 0, x2: 0.5, y2: 0.5,\n"
"                                stop: 0 #25CCF7, stop: 1 #1B9CFC);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setObjectName("tableWidget")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(20)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(4, item)

        self.tableWidget.horizontalHeader().setMinimumSectionSize(180)
        self.tableWidget.verticalHeader().setDefaultSectionSize(38)
# ----------------------------------------------------------------------------------

        self.DMD_ld_btn = QtWidgets.QPushButton(self.centralwidget)
        self.DMD_ld_btn.setGeometry(QtCore.QRect(1010, 750, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DMD_ld_btn.setFont(font)
        self.DMD_ld_btn.setStyleSheet("color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(112, 161, 255,1.0), stop:1 rgba(55, 66, 250,1.0));\n"
"    border-radius: 20px;")
        self.DMD_ld_btn.clicked.connect(self.ShowDatabase)
        self.DMD_ld_btn.setObjectName("DMD_ld_btn")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 140, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: rgb(58, 134, 255);\n"
"    background-color: white;\n"
"    border: 2px solid rgb(58, 134, 255);\n"
"    border-radius: 20px;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3.raise_()
        self.label.raise_()
        self.DMD_back_btn.raise_()
        self.label_2.raise_()
        self.tableWidget.raise_()
        self.DMD_ld_btn.raise_()
        self.label_4.raise_()
        DoctorManagementDatabase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DoctorManagementDatabase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        DoctorManagementDatabase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DoctorManagementDatabase)
        self.statusbar.setObjectName("statusbar")
        DoctorManagementDatabase.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(DoctorManagementDatabase)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(DoctorManagementDatabase)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOption.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DoctorManagementDatabase)
        QtCore.QMetaObject.connectSlotsByName(DoctorManagementDatabase)

        self.actionAbout.triggered.connect(self.openAbout)
        self.actionExit.triggered.connect(DoctorManagementDatabase.close)

    def retranslateUi(self, DoctorManagementDatabase):
        _translate = QtCore.QCoreApplication.translate
        DoctorManagementDatabase.setWindowTitle(_translate("DoctorManagementDatabase", "HMS - Doctor Management Database"))
        self.label.setText(_translate("DoctorManagementDatabase", "                   Doctor Management Database"))
        self.DMD_back_btn.setText(_translate("DoctorManagementDatabase", "Back"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DoctorManagementDatabase", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DoctorManagementDatabase", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DoctorManagementDatabase", "Specialization"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DoctorManagementDatabase", "Contact No"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DoctorManagementDatabase", "Date & Time"))
        self.DMD_ld_btn.setText(_translate("DoctorManagementDatabase", "Load Data"))
        self.label_4.setText(_translate("DoctorManagementDatabase", "Doctors Data"))
        self.menuOption.setTitle(_translate("DoctorManagementDatabase", "Option"))
        self.menuHelp.setTitle(_translate("DoctorManagementDatabase", "Help"))
        self.actionExit.setText(_translate("DoctorManagementDatabase", "Exit"))
        self.actionAbout.setText(_translate("DoctorManagementDatabase", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DoctorManagementDatabase = QtWidgets.QMainWindow()
    ui = Ui_DoctorManagementDatabase()
    ui.setupUi(DoctorManagementDatabase)
    DoctorManagementDatabase.show()
    sys.exit(app.exec_())
