# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import images.HMS
from PyQt5.QtWidgets import QMessageBox
from About import Ui_AboutWindow
from SignupWindow import Ui_SignupWindow
from ManagementView import Ui_ManagementView
from PatientView import Ui_PatientView
from covid19 import Ui_CovidWindow
from PharmacistAdminView import Ui_PharmacistAdminView
from DoctorView import Ui_DoctorView
from pymongo import MongoClient


class Ui_OtherWindow(object):
    def openCovid(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CovidWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openSignupWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SignupWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPatientView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PatientView()
        self.ui.setupUi(self.window)
        self.window.show()

    def openManagementView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ManagementView()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPharmacistAdminView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PharmacistAdminView()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDoctorView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_DoctorView()
        self.ui.setupUi(self.window)
        self.window.show()

    def LoginDatabase(self):
        client = MongoClient('localhost:27017')
        db = client.HSMD
        col = db.SIGNUP_DB
        
        LoginUsername = self.UN_TEXT.text()
        LoginPassword = self.PA_TEXT.text()

        check = col.find_one({"USERNAME":LoginUsername,"PASSWORD": LoginPassword})
        if check != None :
            print("User Found !")
            print("check")
            if (check["TYPE"] == "admin"):
                self.openManagementView()
                print("User Admin ! ")
                msg = QMessageBox()
                msg.setWindowTitle("Message")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                msg.setWindowIcon(icon)
                msg.setIcon(QMessageBox.Information)
                msg.setText("User Admin Successfully Loged In! ")
                msg.exec();
                
                
            elif(check["TYPE"] == "visitor"):
                self.openPatientView()
                print("User Visitor ! ")
                msg = QMessageBox()
                msg.setWindowTitle("Message")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                msg.setWindowIcon(icon)
                msg.setIcon(QMessageBox.Information)
                msg.setText("User Visitor Successfully Loged In! ")
                msg.exec();
                
                
            elif(check["TYPE"] == "pharmacist"):
                self.openPharmacistAdminView()
                print("User Pharmacist ! ")
                msg = QMessageBox()
                msg.setWindowTitle("Message")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                msg.setWindowIcon(icon)
                msg.setIcon(QMessageBox.Information)
                msg.setText("User Pharmacist Admin Successfully Loged In! ")
                msg.exec();
                
                
            elif (check["TYPE"] == "doctor"):
                self.openDoctorView()
                print("User Doctor ! ")
                msg = QMessageBox()
                msg.setWindowTitle("Message")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                msg.setWindowIcon(icon)
                msg.setIcon(QMessageBox.Information)
                msg.setText("User Doctor Successfully Loged In! ")
                msg.exec();
                
        else:
            print("User Not Found !")
            msg = QMessageBox()
            msg.setWindowTitle("Message")
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            msg.setWindowIcon(icon)
            msg.setIcon(QMessageBox.Information)
            msg.setText("User Not Found !")
            msg.setInformativeText("Warning','Invalid Username And Password");
            msg.exec();
            
        

    def setupUi(self, OtherWindow):
        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OtherWindow.setWindowIcon(icon)
        OtherWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(OtherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(930, 350, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(930, 470, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.UN_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.UN_TEXT.setGeometry(QtCore.QRect(1140, 340, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.UN_TEXT.setFont(font)
        self.UN_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UN_TEXT.setObjectName("UN_TEXT")


        self.PA_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.PA_TEXT.setGeometry(QtCore.QRect(1140, 460, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PA_TEXT.setFont(font)
        self.PA_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PA_TEXT.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PA_TEXT.setValidator(self.PA_TEXT.setObjectName("PA_TEXT")

        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(1080, 580, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(112, 161, 255,1.0), stop:1 rgba(55, 66, 250,1.0));\n"
"    border-radius: 20px;")
        self.login_btn.clicked.connect(self.LoginDatabase)
        self.login_btn.setObjectName("login_btn")


        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1090, 690, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.register_btn = QtWidgets.QPushButton(self.centralwidget)
        self.register_btn.setGeometry(QtCore.QRect(1230, 680, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.register_btn.setFont(font)
        self.register_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 10px;")
        self.register_btn.clicked.connect(self.openSignupWindow)
        self.register_btn.setObjectName("register_btn")

        self.LW_covid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.LW_covid_btn.setGeometry(QtCore.QRect(1530, 810, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LW_covid_btn.setFont(font)
        self.LW_covid_btn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.LW_covid_btn.clicked.connect(self.openCovid)
        self.LW_covid_btn.setObjectName("LW_covid_btn")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(810, 150, 721, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(280, 10, 81, 81))
        self.label_11.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"image: url(:/newPrefix4/icon.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 851, 801))
        self.label.setStyleSheet("\n"
"image: url(:/newPrefix1/Login.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1060, 260, 261, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_7.setObjectName("label_7")
        self.label.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.UN_TEXT.raise_()
        self.PA_TEXT.raise_()
        self.login_btn.raise_()
        self.label_6.raise_()
        self.register_btn.raise_()
        self.LW_covid_btn.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_11.raise_()
        self.label_7.raise_()
        OtherWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(OtherWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuOption = QtWidgets.QMenu(self.menuBar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        OtherWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(OtherWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(OtherWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOption.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuOption.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(OtherWindow)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow)
        self.actionAbout.triggered.connect(self.openAbout)
        self.actionExit.triggered.connect(OtherWindow.close)

    def retranslateUi(self, OtherWindow):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow.setWindowTitle(_translate("OtherWindow", "HMS - Login Window"))
        self.label_4.setText(_translate("OtherWindow", "Username :"))
        self.label_5.setText(_translate("OtherWindow", "Password :"))
        self.login_btn.setText(_translate("OtherWindow", "Login"))
        self.label_6.setText(_translate("OtherWindow", "New User ? "))
        self.register_btn.setText(_translate("OtherWindow", "Register"))
        self.LW_covid_btn.setToolTip(_translate("OtherWindow", "<html><head/><body><p><span style=\" font-weight:400;\">Check The Status of Covid-19</span></p></body></html>"))
        self.LW_covid_btn.setText(_translate("OtherWindow", "!"))
        self.label_2.setText(_translate("OtherWindow", "   Hospital Management System"))
        self.label_3.setText(_translate("OtherWindow", "Login Here"))
        self.label_7.setText(_translate("OtherWindow", "Welcome Back !"))
        self.menuOption.setTitle(_translate("OtherWindow", "Option"))
        self.menuHelp.setTitle(_translate("OtherWindow", "Help"))
        self.actionExit.setText(_translate("OtherWindow", "Exit"))
        self.actionAbout.setText(_translate("OtherWindow", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow()
    ui.setupUi(OtherWindow)
    OtherWindow.show()
    sys.exit(app.exec_())
