# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatientView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import images.HMS
from PyQt5.QtWidgets import QMessageBox
from About import Ui_AboutWindow
from covid19 import Ui_CovidWindow
from PatientDataForm import Ui_PatientDataForm
from AppointmentManagementDatabase import Ui_AppointmentManagementDatabase


class Ui_PatientView(object):
    def openCovid(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CovidWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPatientDataForm(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PatientDataForm()
        self.ui.setupUi(self.window)
        self.window.show()

    def openAppointmentManagementDatabase(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AppointmentManagementDatabase()
        self.ui.setupUi(self.window)
        self.window.show()

    def logout(self):
        msg = QMessageBox()
        msg.setWindowTitle("Message")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        msg.setWindowIcon(icon)
        msg.setIcon(QMessageBox.Information)
        font = QtGui.QFont()
        font.setPointSize(10)
        msg.setFont(font)
        msg.setText("Visitor Admin Successfully Loged Out")
        msg.exec();
        
    def setupUi(self, PatientView):
        PatientView.setObjectName("PatientView")
        PatientView.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PatientView.setWindowIcon(icon)
        PatientView.setStyleSheet("background-color: rgb(243, 251, 254);")
        self.centralwidget = QtWidgets.QWidget(PatientView)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")


        self.PS_CAOD_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PS_CAOD_btn.setGeometry(QtCore.QRect(990, 200, 451, 251))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PS_CAOD_btn.setFont(font)
        self.PS_CAOD_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.PS_CAOD_btn.clicked.connect(self.openAppointmentManagementDatabase)
        self.PS_CAOD_btn.setObjectName("PS_CAOD_btn")


        self.PS_FFP_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PS_FFP_btn.setGeometry(QtCore.QRect(990, 490, 451, 261))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PS_FFP_btn.setFont(font)
        self.PS_FFP_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.PS_FFP_btn.clicked.connect(self.openPatientDataForm)
        self.PS_FFP_btn.setObjectName("PS_FFP_btn")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 911, 751))
        self.label_2.setStyleSheet("image: url(:/newPrefix5/Patient3.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 10, 81, 81))
        self.label_3.setStyleSheet("image: url(:/newPrefix4/icon.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")


        self.PS_logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PS_logout_btn.setGeometry(QtCore.QRect(1390, 20, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PS_logout_btn.setFont(font)
        self.PS_logout_btn.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 255);")
        self.PS_logout_btn.clicked.connect(PatientView.close)
        self.PS_logout_btn.clicked.connect(self.logout)
        self.PS_logout_btn.setObjectName("PS_logout_btn")


        self.PS_covid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PS_covid_btn.setGeometry(QtCore.QRect(1520, 810, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PS_covid_btn.setFont(font)
        self.PS_covid_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.PS_covid_btn.clicked.connect(self.openCovid)
        self.PS_covid_btn.setObjectName("PS_covid_btn")

        
        self.label_2.raise_()
        self.label.raise_()
        self.PS_CAOD_btn.raise_()
        self.PS_FFP_btn.raise_()
        self.label_3.raise_()
        self.PS_logout_btn.raise_()
        self.PS_covid_btn.raise_()
        PatientView.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(PatientView)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        PatientView.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(PatientView)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(PatientView)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PatientView)
        QtCore.QMetaObject.connectSlotsByName(PatientView)

        self.actionExit.triggered.connect(PatientView.close)
        self.actionAbout.triggered.connect(self.openAbout)

    def retranslateUi(self, PatientView):
        _translate = QtCore.QCoreApplication.translate
        PatientView.setWindowTitle(_translate("PatientView", "HMS - Patient View"))
        self.label.setText(_translate("PatientView", "                    Patient Section"))
        self.PS_CAOD_btn.setText(_translate("PatientView", "Check Appointments of Docter"))
        self.PS_FFP_btn.setText(_translate("PatientView", "Fill the Form of Patient"))
        self.PS_logout_btn.setText(_translate("PatientView", "Logout"))
        self.PS_covid_btn.setToolTip(_translate("PatientView", "<html><head/><body><p><span style=\" font-weight:400;\">Check The Status of Covid-19</span></p></body></html>"))
        self.PS_covid_btn.setText(_translate("PatientView", "!"))
        self.menuFile.setTitle(_translate("PatientView", "Option"))
        self.menuHelp.setTitle(_translate("PatientView", "Help"))
        self.actionExit.setText(_translate("PatientView", "Exit"))
        self.actionAbout.setText(_translate("PatientView", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PatientView = QtWidgets.QMainWindow()
    ui = Ui_PatientView()
    ui.setupUi(PatientView)
    PatientView.show()
    sys.exit(app.exec_())
