# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PharmacistNeeds.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMessageBox
import images.HMS
from About import Ui_AboutWindow
from PharmacistDatabase import Ui_PharmacistDatabase
from pymongo import MongoClient


class Ui_PharmacistNeeds(object):
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPharmacistDatabase(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PharmacistDatabase()
        self.ui.setupUi(self.window)
        self.window.show()

    def SubmitDatabase(self):
          client = MongoClient('localhost:27017')
          db = client.HSMD
          col = db.Pharma_DB

          StockId = self.PDAS_ID_TEXT.text().upper()
          ProductName = self.PDAS_NP_TEXT.text().title()
          StockNeed = self.PDAS_Q_TEXT.text().title()
          ReadyDate = self.PDAS_AD_TEXT.text()

          col.insert_one(
            {
                "ID": StockId,
                "PRODUCT NAME": ProductName,
                "STOCK NEED": StockNeed,
                "READY DATE": ReadyDate
                })
          print ('\nData Inserted Successfully\n')
          msg = QMessageBox()
          msg.setWindowTitle("Message")
          icon = QtGui.QIcon()
          icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
          msg.setWindowIcon(icon)
          msg.setIcon(QMessageBox.Information)
          font = QtGui.QFont()
          font.setPointSize(10)
          msg.setFont(font)
          msg.setText("Data Inserted Successfully")
          msg.exec();

    def UpdateDatabase(self):
          client = MongoClient('localhost:27017')
          db = client.HSMD
          col = db.Pharma_DB

          StockId = self.PDAS_ID_TEXT.text().upper()
          ProductName = self.PDAS_NP_TEXT.text().title()
          StockNeed = self.PDAS_Q_TEXT.text().title()
          ReadyDate = self.PDAS_AD_TEXT.text()

          col.update_one(
	    {"ID": StockId},
	    {"$set": {"PRODUCT NAME": ProductName,"STOCK NEED": StockNeed,"READY DATE": ReadyDate}})
          print ("\nRecords Updated Successfully\n")
          msg = QMessageBox()
          msg.setWindowTitle("Message")
          icon = QtGui.QIcon()
          icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
          msg.setWindowIcon(icon)
          msg.setIcon(QMessageBox.Information)
          font = QtGui.QFont()
          font.setPointSize(10)
          msg.setFont(font)
          msg.setText("Record Updated Successfully")
          msg.exec();

    def DeleteDatabase(self):
          client = MongoClient('localhost:27017')
          db = client.HSMD
          col = db.Pharma_DB
          
          StockId = self.PDAS_ID_TEXT.text().upper()
          col.delete_many({"ID":StockId})
          print ('\nDeletion Successful\n')
          msg = QMessageBox()
          msg.setWindowTitle("Message")
          icon = QtGui.QIcon()
          icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
          msg.setWindowIcon(icon)
          msg.setIcon(QMessageBox.Information)
          font = QtGui.QFont()
          font.setPointSize(10)
          msg.setFont(font)
          msg.setText("Record Deleted Successfully")
          msg.exec();


    def setupUi(self, PharmacistNeeds):
        PharmacistNeeds.setObjectName("PharmacistNeeds")
        PharmacistNeeds.resize(1600, 900)
        PharmacistNeeds.setStyleSheet("background-color: rgb(230, 248, 252);")
        self.centralwidget = QtWidgets.QWidget(PharmacistNeeds)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.PDAS_back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PDAS_back_btn.setGeometry(QtCore.QRect(1410, 20, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PDAS_back_btn.setFont(font)
        self.PDAS_back_btn.clicked.connect(PharmacistNeeds.close)
        self.PDAS_back_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(58, 68, 255);\n"
"border-radius: 20px;")
        self.PDAS_back_btn.setObjectName("PDAS_back_btn")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 81, 81))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/newPrefix4/icon.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(920, 210, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(920, 310, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(920, 420, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(920, 510, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.PDAS_ID_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.PDAS_ID_TEXT.setGeometry(QtCore.QRect(1160, 210, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PDAS_ID_TEXT.setFont(font)
        self.PDAS_ID_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PDAS_ID_TEXT.setObjectName("PDAS_ID_TEXT")
        self.PDAS_NP_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.PDAS_NP_TEXT.setGeometry(QtCore.QRect(1160, 310, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PDAS_NP_TEXT.setFont(font)
        self.PDAS_NP_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PDAS_NP_TEXT.setObjectName("PDAS_NP_TEXT")
        self.PDAS_Q_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.PDAS_Q_TEXT.setGeometry(QtCore.QRect(1160, 410, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PDAS_Q_TEXT.setFont(font)
        self.PDAS_Q_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PDAS_Q_TEXT.setObjectName("PDAS_Q_TEXT")
        self.PDAS_AD_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.PDAS_AD_TEXT.setGeometry(QtCore.QRect(1160, 510, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PDAS_AD_TEXT.setFont(font)
        self.PDAS_AD_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PDAS_AD_TEXT.setObjectName("PDAS_AD_TEXT")

        self.PDAS_submit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PDAS_submit_btn.setGeometry(QtCore.QRect(910, 630, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PDAS_submit_btn.setFont(font)
        self.PDAS_submit_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.PDAS_submit_btn.clicked.connect(self.SubmitDatabase)
        self.PDAS_submit_btn.setObjectName("PDAS_submit_btn")

        self.PDAS_update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PDAS_update_btn.setGeometry(QtCore.QRect(1120, 630, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PDAS_update_btn.setFont(font)
        self.PDAS_update_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.PDAS_update_btn.clicked.connect(self.UpdateDatabase)
        self.PDAS_update_btn.setObjectName("PDAS_update_btn")

        self.PDAS_delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PDAS_delete_btn.setGeometry(QtCore.QRect(1330, 630, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PDAS_delete_btn.setFont(font)
        self.PDAS_delete_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.PDAS_delete_btn.clicked.connect(self.DeleteDatabase)
        self.PDAS_delete_btn.setObjectName("PDAS_delete_btn")

        self.PDAS_view_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PDAS_view_btn.setGeometry(QtCore.QRect(1120, 750, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PDAS_view_btn.setFont(font)
        self.PDAS_view_btn.setStyleSheet("color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(112, 161, 255,1.0), stop:1 rgba(55, 66, 250,1.0));\n"
"    border-radius: 20px;")
        self.PDAS_view_btn.clicked.connect(self.openPharmacistDatabase)
        self.PDAS_view_btn.setObjectName("PDAS_view_btn")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 791, 841))
        self.label_7.setStyleSheet("image: url(:/newPrefix5/Pharmacy.jpg);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.label.raise_()
        self.PDAS_back_btn.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.PDAS_ID_TEXT.raise_()
        self.PDAS_NP_TEXT.raise_()
        self.PDAS_Q_TEXT.raise_()
        self.PDAS_AD_TEXT.raise_()
        self.PDAS_submit_btn.raise_()
        self.PDAS_update_btn.raise_()
        self.PDAS_delete_btn.raise_()
        self.PDAS_view_btn.raise_()
        PharmacistNeeds.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(PharmacistNeeds)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuOption = QtWidgets.QMenu(self.menuBar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        PharmacistNeeds.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(PharmacistNeeds)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(PharmacistNeeds)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOption.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuOption.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PharmacistNeeds)
        QtCore.QMetaObject.connectSlotsByName(PharmacistNeeds)

        self.actionAbout.triggered.connect(self.openAbout)
        self.actionExit.triggered.connect(PharmacistNeeds.close)

    def retranslateUi(self, PharmacistNeeds):
        _translate = QtCore.QCoreApplication.translate
        PharmacistNeeds.setWindowTitle(_translate("PharmacistNeeds", "HMS - Pharmacist Data Adding Section"))
        self.label.setText(_translate("PharmacistNeeds", "              Pharmacist Data Adding Section"))
        self.PDAS_back_btn.setText(_translate("PharmacistNeeds", "Back"))
        self.label_3.setText(_translate("PharmacistNeeds", "ID :"))
        self.label_4.setText(_translate("PharmacistNeeds", "Name Of Product :"))
        self.label_5.setText(_translate("PharmacistNeeds", "Quantity :"))
        self.label_6.setText(_translate("PharmacistNeeds", "Availability Data :"))
        self.PDAS_ID_TEXT.setToolTip(_translate("PharmacistNeeds", "<html><head/><body><p>POR00001</p></body></html>"))
        self.PDAS_submit_btn.setText(_translate("PharmacistNeeds", "Submit"))
        self.PDAS_update_btn.setText(_translate("PharmacistNeeds", "Update"))
        self.PDAS_delete_btn.setText(_translate("PharmacistNeeds", "Delete"))
        self.PDAS_view_btn.setText(_translate("PharmacistNeeds", "View"))
        self.menuOption.setTitle(_translate("PharmacistNeeds", "Option"))
        self.menuHelp.setTitle(_translate("PharmacistNeeds", "Help"))
        self.actionExit.setText(_translate("PharmacistNeeds", "Exit"))
        self.actionAbout.setText(_translate("PharmacistNeeds", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PharmacistNeeds = QtWidgets.QMainWindow()
    ui = Ui_PharmacistNeeds()
    ui.setupUi(PharmacistNeeds)
    PharmacistNeeds.show()
    sys.exit(app.exec_())
