# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PharmacistManagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMessageBox
import images.HMS
from About import Ui_AboutWindow
from covid19 import Ui_CovidWindow
from StockOfGoodsManagement import Ui_StockOfGoodsManagement
from PharmacistDatabase import Ui_PharmacistDatabase


class Ui_PharmacistManagement(object):
    def openCovid(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CovidWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPharmacistDatabase(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PharmacistDatabase()
        self.ui.setupUi(self.window)
        self.window.show()

    def openStockOfGoodsManagement(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_StockOfGoodsManagement()
        self.ui.setupUi(self.window)
        self.window.show()

    
        
    def setupUi(self, PharmacistManagement):
        PharmacistManagement.setObjectName("PharmacistManagement")
        PharmacistManagement.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PharmacistManagement.setWindowIcon(icon)
        PharmacistManagement.setStyleSheet("background-color: rgb(168, 221, 235);")
        self.centralwidget = QtWidgets.QWidget(PharmacistManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 81, 81))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/newPrefix4/icon.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.PM_logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PM_logout_btn.setGeometry(QtCore.QRect(1380, 20, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PM_logout_btn.setFont(font)
        self.PM_logout_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(58, 68, 255);\n"
"border-radius: 20px;")
        self.PM_logout_btn.clicked.connect(PharmacistManagement.close)
        self.PM_logout_btn.setObjectName("PM_logout_btn")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, -10, 871, 1031))
        self.label_3.setStyleSheet("image: url(:/newPrefix5/Pharmacy Admin.jpg);\n"
"\n"
"background-color: rgb(163, 221, 235);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")


        self.PM_COG_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PM_COG_btn.setGeometry(QtCore.QRect(970, 170, 511, 271))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PM_COG_btn.setFont(font)
        self.PM_COG_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.PM_COG_btn.clicked.connect(self.openPharmacistDatabase)
        self.PM_COG_btn.setObjectName("PM_COG_btn")


        self.PM_AGD_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PM_AGD_btn.setGeometry(QtCore.QRect(970, 500, 511, 271))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PM_AGD_btn.setFont(font)
        self.PM_AGD_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.PM_AGD_btn.clicked.connect(self.openStockOfGoodsManagement)
        self.PM_AGD_btn.setObjectName("PM_AGD_btn")


        self.PM_covid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PM_covid_btn.setGeometry(QtCore.QRect(1520, 810, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PM_covid_btn.setFont(font)
        self.PM_covid_btn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.PM_covid_btn.clicked.connect(self.openCovid)
        self.PM_covid_btn.setObjectName("PM_covid_btn")


        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.PM_logout_btn.raise_()
        self.PM_COG_btn.raise_()
        self.PM_AGD_btn.raise_()
        self.PM_covid_btn.raise_()
        PharmacistManagement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PharmacistManagement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        PharmacistManagement.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(PharmacistManagement)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(PharmacistManagement)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOption.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PharmacistManagement)
        QtCore.QMetaObject.connectSlotsByName(PharmacistManagement)

        self.actionAbout.triggered.connect(self.openAbout)
        self.actionExit.triggered.connect(PharmacistManagement.close)

    def retranslateUi(self, PharmacistManagement):
        _translate = QtCore.QCoreApplication.translate
        PharmacistManagement.setWindowTitle(_translate("PharmacistManagement", "HMS - Pharmacist Management"))
        self.label.setText(_translate("PharmacistManagement", "                 Pharmacist Management Section"))
        self.PM_logout_btn.setText(_translate("PharmacistManagement", "Back"))
        self.PM_COG_btn.setText(_translate("PharmacistManagement", "Check the Orders of Goods"))
        self.PM_AGD_btn.setText(_translate("PharmacistManagement", "Add Goods Data"))
        self.PM_covid_btn.setToolTip(_translate("PharmacistManagement", "<html><head/><body><p><span style=\" font-weight:400;\">Check The Status of Covid-19</span></p></body></html>"))
        self.PM_covid_btn.setText(_translate("PharmacistManagement", "!"))
        self.menuOption.setTitle(_translate("PharmacistManagement", "Option"))
        self.menuHelp.setTitle(_translate("PharmacistManagement", "Help"))
        self.actionExit.setText(_translate("PharmacistManagement", "Exit"))
        self.actionAbout.setText(_translate("PharmacistManagement", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PharmacistManagement = QtWidgets.QMainWindow()
    ui = Ui_PharmacistManagement()
    ui.setupUi(PharmacistManagement)
    PharmacistManagement.show()
    sys.exit(app.exec_())
