# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PharmacistAdminView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import images.HMS
from About import Ui_AboutWindow
from PharmacistNeeds import Ui_PharmacistNeeds
from covid19 import Ui_CovidWindow
from StockOfGoodsDatabase import Ui_StockOfGoodsDatabase


class Ui_PharmacistAdminView(object):
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPharmacistNeeds(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PharmacistNeeds()
        self.ui.setupUi(self.window)
        self.window.show()

    def openStockOfGoodsDatabase(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_StockOfGoodsDatabase()
        self.ui.setupUi(self.window)
        self.window.show()

    def openCovid(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CovidWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def logout(self):
        msg = QMessageBox()
        msg.setWindowTitle("Message")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        msg.setWindowIcon(icon)
        msg.setIcon(QMessageBox.Information)
        font = QtGui.QFont()
        font.setPointSize(10)
        msg.setFont(font)
        msg.setText("Pharma Admin Successfully Loged Out")
        msg.exec();
        
    def setupUi(self, PharmacistAdminView):
        PharmacistAdminView.setObjectName("PharmacistAdminView")
        PharmacistAdminView.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PharmacistAdminView.setWindowIcon(icon)
        PharmacistAdminView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(PharmacistAdminView)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 81, 81))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/newPrefix4/icon.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")


        self.PA_logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PA_logout_btn.setGeometry(QtCore.QRect(1380, 20, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PA_logout_btn.setFont(font)
        self.PA_logout_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(58, 68, 255);\n"
"border-radius: 20px;")
        self.PA_logout_btn.clicked.connect(PharmacistAdminView.close)
        self.PA_logout_btn.clicked.connect(self.logout)
        self.PA_logout_btn.setObjectName("PA_logout_btn")


        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 911, 821))
        self.label_3.setStyleSheet("image: url(:/newPrefix5/Pharmacy2.png.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.PA_CSG_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PA_CSG_btn.setGeometry(QtCore.QRect(980, 190, 471, 251))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PA_CSG_btn.setFont(font)
        self.PA_CSG_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.PA_CSG_btn.clicked.connect(self.openStockOfGoodsDatabase)
        self.PA_CSG_btn.setObjectName("PA_CSG_btn")


        self.PA_ARGD_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PA_ARGD_btn.setGeometry(QtCore.QRect(980, 490, 471, 261))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PA_ARGD_btn.setFont(font)
        self.PA_ARGD_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.PA_ARGD_btn.clicked.connect(self.openPharmacistNeeds)
        self.PA_ARGD_btn.setObjectName("PA_ARGD_btn")

        self.PA_covid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PA_covid_btn.setGeometry(QtCore.QRect(1520, 810, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PA_covid_btn.setFont(font)
        self.PA_covid_btn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.PA_covid_btn.clicked.connect(self.openCovid)
        self.PA_covid_btn.setObjectName("PA_covid_btn")


        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.PA_logout_btn.raise_()
        self.PA_CSG_btn.raise_()
        self.PA_ARGD_btn.raise_()
        self.PA_covid_btn.raise_()
        PharmacistAdminView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PharmacistAdminView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        PharmacistAdminView.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(PharmacistAdminView)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(PharmacistAdminView)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOption.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PharmacistAdminView)
        QtCore.QMetaObject.connectSlotsByName(PharmacistAdminView)

        self.actionAbout.triggered.connect(self.openAbout)
        self.actionExit.triggered.connect(PharmacistAdminView.close)

    def retranslateUi(self, PharmacistAdminView):
        _translate = QtCore.QCoreApplication.translate
        PharmacistAdminView.setWindowTitle(_translate("PharmacistAdminView", "HMS - Pharmacist Admin View"))
        self.label.setText(_translate("PharmacistAdminView", "                 Pharmacist Admin Section"))
        self.PA_logout_btn.setText(_translate("PharmacistAdminView", "Logout"))
        self.PA_CSG_btn.setText(_translate("PharmacistAdminView", "Check the Stock of Goods"))
        self.PA_ARGD_btn.setText(_translate("PharmacistAdminView", "Add Requested Goods Data"))
        self.PA_covid_btn.setToolTip(_translate("PharmacistAdminView", "<html><head/><body><p><span style=\" font-weight:400;\">Check The Status of Covid-19</span></p></body></html>"))
        self.PA_covid_btn.setText(_translate("PharmacistAdminView", "!"))
        self.menuOption.setTitle(_translate("PharmacistAdminView", "Option"))
        self.menuHelp.setTitle(_translate("PharmacistAdminView", "Help"))
        self.actionExit.setText(_translate("PharmacistAdminView", "Exit"))
        self.actionAbout.setText(_translate("PharmacistAdminView", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PharmacistAdminView = QtWidgets.QMainWindow()
    ui = Ui_PharmacistAdminView()
    ui.setupUi(PharmacistAdminView)
    PharmacistAdminView.show()
    sys.exit(app.exec_())
