# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignupWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import images.HMS
from PyQt5.QtWidgets import QMessageBox
from pymongo import MongoClient
from datetime import datetime
from About import Ui_AboutWindow
from ManagementView import Ui_ManagementView
from PatientView import Ui_PatientView
from PharmacistAdminView import Ui_PharmacistAdminView
from DoctorView import Ui_DoctorView




class Ui_SignupWindow(object):
    def openLogin(self):
        OtherWindow.window = QtWidgets.QMainWindow()
        OtherWindow.ui = Ui_OtherWindow()
        OtherWindow.ui.setupUi(OtherWindow.window)
        OtherWindow.window.show()
        
        
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPatientView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PatientView()
        self.ui.setupUi(self.window)
        self.window.show()

    def openManagementView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ManagementView()
        self.ui.setupUi(self.window)
        self.window.show()

    def openPharmacistAdminView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PharmacistAdminView()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDoctorView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_DoctorView()
        self.ui.setupUi(self.window)
        self.window.show()

    def LoginDatabase(self):
        client = MongoClient('localhost:27017')
        db = client.HSMD
        col = db.SIGNUP_DB

        SignupName = self.lineEdit.text().title()
        SignupUsername = self.lineEdit_2.text()
        SignupType = self.lineEdit_3.text()
        SignupGender = self.lineEdit_4.text().title()
        SignupAddress = self.lineEdit_5.text().title()
        SignupPassword = self.lineEdit_6.text()
        
        
        dt = datetime.now()
        d = dt.strftime("%B %d,%Y  %H:%M:%S")

        col.insert_one(
            {
                "NAME": SignupName,
                "USERNAME":SignupUsername,
                "TYPE":SignupType,
                "GENDER": SignupGender,
                "ADDRESS":SignupAddress,
                "PASSWORD": SignupPassword,
                "DATE & TIME": d
                })
            
        print ('\nInserted data successfully\n')

        if (SignupType == "admin" or SignupType == "Admin" ):
            self.openManagementView()
            msg = QMessageBox()
            msg.setWindowTitle("Message")
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            msg.setWindowIcon(icon)
            msg.setIcon(QMessageBox.Information)
            msg.setText(" New Admin Profile Created and\n You have Redireted to Admin Section ! ")
            msg.exec();
            
            
        elif(SignupType == "visitor" or SignupType == "Visitor"):
            self.openPatientView()
            msg = QMessageBox()
            msg.setWindowTitle("Message")
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            msg.setWindowIcon(icon)
            msg.setIcon(QMessageBox.Information)
            msg.setText(" New Visitor Profile Created and\n You have Redireted to Section ! ")
            msg.exec();
            
            
        elif(SignupType == "pharmacist" or SignupType == "Pharmacist"):
            self.openPharmacistAdminView()
            msg = QMessageBox()
            msg.setWindowTitle("Message")
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            msg.setWindowIcon(icon)
            msg.setIcon(QMessageBox.Information)
            msg.setText(" New Pharmacist Profile Created and\n You have Redireted to Section ! ")
            msg.exec();
            
            
        elif(SignupType == "doctor" or SignupType == "Doctor"):
            self.openDoctorView()
            msg = QMessageBox()
            msg.setWindowTitle("Message")
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            msg.setWindowIcon(icon)
            msg.setIcon(QMessageBox.Information)
            msg.setText(" New Doctor Profile Created and\n You have Redireted to Section ! ")
            msg.exec();
            
            
    def setupUi(self, SignupWindow):
        SignupWindow.setObjectName("SignupWindow")
        SignupWindow.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SignupWindow.setWindowIcon(icon)
        SignupWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(SignupWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 10, 81, 71))
        self.label_7.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"image: url(:/win icon/icon.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 90, 881, 841))
        self.label.setStyleSheet("image: url(:/newPrefix1/Register.jpg);;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(790, 130, 721, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(1060, 240, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(900, 240, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(1060, 320, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(900, 320, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(1060, 400, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(900, 400, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(1060, 480, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(900, 475, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(1060, 560, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(900, 560, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(1060, 640, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(900, 640, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(900, 720, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1070, 770, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.pushButton.clicked.connect(self.LoginDatabase)
        self.pushButton.setObjectName("pushButton")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(280, 10, 81, 81))
        self.label_11.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"image: url(:/newPrefix4/icon.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1280, 800, 281, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius: 10px;\n"
"color: rgb(0, 0, 255);\n"
"background-color: rgb(250, 248, 253);")
        self.pushButton_2.clicked.connect(SignupWindow.close)
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_7.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.label_4.raise_()
        self.lineEdit_2.raise_()
        self.label_5.raise_()
        self.lineEdit_3.raise_()
        self.label_6.raise_()
        self.lineEdit_4.raise_()
        self.label_8.raise_()
        self.lineEdit_5.raise_()
        self.label_9.raise_()
        self.lineEdit_6.raise_()
        self.label_10.raise_()
        self.radioButton.raise_()
        self.pushButton.raise_()
        self.label_11.raise_()
        self.pushButton_2.raise_()
        SignupWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(SignupWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuOption = QtWidgets.QMenu(self.menuBar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        SignupWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(SignupWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(SignupWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOption.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuOption.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SignupWindow)
        QtCore.QMetaObject.connectSlotsByName(SignupWindow)

        self.actionAbout.triggered.connect(self.openAbout)
        self.actionExit.triggered.connect(SignupWindow.close)

    def retranslateUi(self, SignupWindow):
        _translate = QtCore.QCoreApplication.translate
        SignupWindow.setWindowTitle(_translate("SignupWindow", "HMS - Register"))
        self.label_2.setText(_translate("SignupWindow", "   Hospital Management System"))
        self.label_3.setText(_translate("SignupWindow", "Register"))
        self.label_4.setText(_translate("SignupWindow", "Name :"))
        self.label_5.setText(_translate("SignupWindow", "Username :"))
        self.lineEdit_3.setToolTip(_translate("SignupWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">admin / docter / pharmacist / visitors</span></p></body></html>"))
        self.label_6.setToolTip(_translate("SignupWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">admin / docter / pharmacist / visitors</span></p></body></html>"))
        self.label_6.setText(_translate("SignupWindow", "Type :"))
        self.label_8.setText(_translate("SignupWindow", "Gender :"))
        self.label_9.setText(_translate("SignupWindow", "Address :"))
        self.label_10.setText(_translate("SignupWindow", "Password :"))
        self.radioButton.setText(_translate("SignupWindow", "I COMPLY WITH ALL REGULATIONS IN THIS HOSPITAL"))
        self.pushButton.setText(_translate("SignupWindow", "Create"))
        self.pushButton_2.setText(_translate("SignupWindow", "Already Registered ? Go to Login"))
        self.menuOption.setTitle(_translate("SignupWindow", "Option"))
        self.menuHelp.setTitle(_translate("SignupWindow", "Help"))
        self.actionExit.setText(_translate("SignupWindow", "Exit"))
        self.actionAbout.setText(_translate("SignupWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignupWindow = QtWidgets.QMainWindow()
    ui = Ui_SignupWindow()
    ui.setupUi(SignupWindow)
    SignupWindow.show()
    sys.exit(app.exec_())
