# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockOfGoodsManagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMessageBox
import images.HMS
from About import Ui_AboutWindow
from StockOfGoodsDatabase import Ui_StockOfGoodsDatabase
from pymongo import MongoClient


class Ui_StockOfGoodsManagement(object):
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openStockOfGoodsDatabase(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_StockOfGoodsDatabase()
        self.ui.setupUi(self.window)
        self.window.show()

    def SubmitDatabase(self):
          client = MongoClient('localhost:27017')
          db = client.HSMD
          col = db.SOG_DB

          ProductId = self.SOGM_PI_TEXT.text().upper()
          ProductSupplier = self.SOGM_S_TEXT.text().title()
          ProductName = self.SOGM_NP_TEXT.text().title()
          ProductPrice = self.SOGM_PP_TEXT.text()
          ProductStock = self.SOGM_SP_TEXT.text().title()
          PackagingDate = self.SOGM_P_TEXT.text()
          DateofEntry = self.SOGM_DOE_TEXT.text()

          col.insert_one(
            {
                "ID": ProductId,
                "SUPPLIER":ProductSupplier,
                "PRODUCT NAME": ProductName,
                "PRODUCT PRICE":ProductPrice,
                "STOCK": ProductStock,
                "PACKAGING DATE": PackagingDate,
                "DATE OF ENTRY": DateofEntry
                })
          print ('\nInserted data successfully\n')
          msg = QMessageBox()
          msg.setWindowTitle("Message")
          icon = QtGui.QIcon()
          icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
          msg.setWindowIcon(icon)
          msg.setIcon(QMessageBox.Information)
          font = QtGui.QFont()
          font.setPointSize(10)
          msg.setFont(font)
          msg.setText("Data Inserted Successfully")
          msg.exec();

    def UpdateDatabase(self):
          client = MongoClient('localhost:27017')
          db = client.HSMD
          col = db.SOG_DB

          ProductId = self.SOGM_PI_TEXT.text().upper()
          ProductSupplier = self.SOGM_S_TEXT.text().title()
          ProductName = self.SOGM_NP_TEXT.text().title()
          ProductPrice = self.SOGM_PP_TEXT.text()
          ProductStock = self.SOGM_SP_TEXT.text().title()
          PackagingDate = self.SOGM_P_TEXT.text()
          DateofEntry = self.SOGM_DOE_TEXT.text()

          col.update_one(
	    {"ID": ProductId},
	    {"$set": {"SUPPLIER":ProductSupplier,"PRODUCT NAME":ProductName,"PRODUCT PRICE":ProductPrice,"STOCK":ProductStock,"PACKAGING DATE":PackagingDate,"DATE OF ENTRY":DateofEntry}})
          print ("\nRecords updated successfully\n")
          msg = QMessageBox()
          msg.setWindowTitle("Message")
          icon = QtGui.QIcon()
          icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
          msg.setWindowIcon(icon)
          msg.setIcon(QMessageBox.Information)
          font = QtGui.QFont()
          font.setPointSize(10)
          msg.setFont(font)
          msg.setText("Record Updated Successfully")
          msg.exec();

    def DeleteDatabase(self):
          client = MongoClient('localhost:27017')
          db = client.HSMD
          col = db.SOG_DB
          
          ProductId = self.SOGM_PI_TEXT.text().upper()
          col.delete_many({"ID":ProductId})
          print ('\nDeletion successful\n')
          msg = QMessageBox()
          msg.setWindowTitle("Message")
          icon = QtGui.QIcon()
          icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
          msg.setWindowIcon(icon)
          msg.setIcon(QMessageBox.Information)
          font = QtGui.QFont()
          font.setPointSize(10)
          msg.setFont(font)
          msg.setText("Record Deleted Successfully")
          msg.exec();


    def setupUi(self, StockOfGoodsManagement):
        StockOfGoodsManagement.setObjectName("StockOfGoodsManagement")
        StockOfGoodsManagement.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StockOfGoodsManagement.setWindowIcon(icon)
        StockOfGoodsManagement.setStyleSheet("background-color: rgb(230, 248, 252);")
        self.centralwidget = QtWidgets.QWidget(StockOfGoodsManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 71, 71))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/newPrefix4/icon.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1601, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.SOGM_back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.SOGM_back_btn.setGeometry(QtCore.QRect(1410, 20, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SOGM_back_btn.setFont(font)
        self.SOGM_back_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(58, 68, 255);\n"
"border-radius: 20px;")
        self.SOGM_back_btn.clicked.connect(StockOfGoodsManagement.close)
        self.SOGM_back_btn.setObjectName("SOGM_back_btn")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 160, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(780, 250, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(780, 340, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(780, 430, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(780, 520, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(780, 610, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(780, 700, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.SOGM_PI_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.SOGM_PI_TEXT.setGeometry(QtCore.QRect(1020, 159, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SOGM_PI_TEXT.setFont(font)
        self.SOGM_PI_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SOGM_PI_TEXT.setObjectName("SOGM_PI_TEXT")
        self.SOGM_S_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.SOGM_S_TEXT.setGeometry(QtCore.QRect(1020, 250, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SOGM_S_TEXT.setFont(font)
        self.SOGM_S_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SOGM_S_TEXT.setObjectName("SOGM_S_TEXT")
        self.SOGM_NP_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.SOGM_NP_TEXT.setGeometry(QtCore.QRect(1020, 340, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SOGM_NP_TEXT.setFont(font)
        self.SOGM_NP_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SOGM_NP_TEXT.setObjectName("SOGM_NP_TEXT")
        self.SOGM_PP_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.SOGM_PP_TEXT.setGeometry(QtCore.QRect(1020, 430, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SOGM_PP_TEXT.setFont(font)
        self.SOGM_PP_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SOGM_PP_TEXT.setObjectName("SOGM_PP_TEXT")
        self.SOGM_SP_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.SOGM_SP_TEXT.setGeometry(QtCore.QRect(1020, 520, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SOGM_SP_TEXT.setFont(font)
        self.SOGM_SP_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SOGM_SP_TEXT.setObjectName("SOGM_SP_TEXT")
        self.SOGM_P_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.SOGM_P_TEXT.setGeometry(QtCore.QRect(1020, 610, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SOGM_P_TEXT.setFont(font)
        self.SOGM_P_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SOGM_P_TEXT.setObjectName("SOGM_P_TEXT")
        self.SOGM_DOE_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.SOGM_DOE_TEXT.setGeometry(QtCore.QRect(1020, 700, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SOGM_DOE_TEXT.setFont(font)
        self.SOGM_DOE_TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SOGM_DOE_TEXT.setObjectName("SOGM_DOE_TEXT")

        self.SOGM_submit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.SOGM_submit_btn.setGeometry(QtCore.QRect(1400, 250, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SOGM_submit_btn.setFont(font)
        self.SOGM_submit_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.SOGM_submit_btn.clicked.connect(self.SubmitDatabase)
        self.SOGM_submit_btn.setObjectName("SOGM_submit_btn")

        self.SOGM_update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.SOGM_update_btn.setGeometry(QtCore.QRect(1400, 350, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SOGM_update_btn.setFont(font)
        self.SOGM_update_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.SOGM_update_btn.clicked.connect(self.UpdateDatabase)
        self.SOGM_update_btn.setObjectName("SOGM_update_btn")

        self.SOGM_delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.SOGM_delete_btn.setGeometry(QtCore.QRect(1400, 450, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SOGM_delete_btn.setFont(font)
        self.SOGM_delete_btn.setStyleSheet("color: rgb(58, 134, 255);\n"
"background-color: white ;\n"
"border: 2px solid rgb(58, 134, 255);\n"
"border-radius: 20px;")
        self.SOGM_delete_btn.clicked.connect(self.DeleteDatabase)
        self.SOGM_delete_btn.setObjectName("SOGM_delete_btn")

        self.SOGM_view_btn = QtWidgets.QPushButton(self.centralwidget)
        self.SOGM_view_btn.setGeometry(QtCore.QRect(1400, 550, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SOGM_view_btn.setFont(font)
        self.SOGM_view_btn.setStyleSheet("color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(112, 161, 255,1.0), stop:1 rgba(55, 66, 250,1.0));\n"
"    border-radius: 20px;")
        self.SOGM_view_btn.clicked.connect(self.openStockOfGoodsDatabase)
        self.SOGM_view_btn.setObjectName("SOGM_view_btn")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 761, 781))
        self.label_10.setStyleSheet("image: url(:/newPrefix5/Pharmacy.jpg);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_10.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.SOGM_back_btn.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.SOGM_PI_TEXT.raise_()
        self.SOGM_S_TEXT.raise_()
        self.SOGM_NP_TEXT.raise_()
        self.SOGM_PP_TEXT.raise_()
        self.SOGM_SP_TEXT.raise_()
        self.SOGM_P_TEXT.raise_()
        self.SOGM_DOE_TEXT.raise_()
        self.SOGM_submit_btn.raise_()
        self.SOGM_update_btn.raise_()
        self.SOGM_delete_btn.raise_()
        self.SOGM_view_btn.raise_()
        StockOfGoodsManagement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StockOfGoodsManagement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        StockOfGoodsManagement.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(StockOfGoodsManagement)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(StockOfGoodsManagement)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOption.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(StockOfGoodsManagement)
        QtCore.QMetaObject.connectSlotsByName(StockOfGoodsManagement)

        self.actionAbout.triggered.connect(self.openAbout)
        self.actionExit.triggered.connect(StockOfGoodsManagement.close)

    def retranslateUi(self, StockOfGoodsManagement):
        _translate = QtCore.QCoreApplication.translate
        StockOfGoodsManagement.setWindowTitle(_translate("StockOfGoodsManagement", "HMS - Stock Of Goods Management"))
        self.label.setText(_translate("StockOfGoodsManagement", "                Stock of Goods Management"))
        self.SOGM_back_btn.setText(_translate("StockOfGoodsManagement", "Back"))
        self.label_3.setText(_translate("StockOfGoodsManagement", "Product Id :"))
        self.label_4.setText(_translate("StockOfGoodsManagement", "Supplier :"))
        self.label_5.setText(_translate("StockOfGoodsManagement", "Name of Product :"))
        self.label_6.setText(_translate("StockOfGoodsManagement", "Price of Product :"))
        self.label_7.setText(_translate("StockOfGoodsManagement", "Stock of Product:"))
        self.label_8.setText(_translate("StockOfGoodsManagement", "Packaging :"))
        self.label_9.setText(_translate("StockOfGoodsManagement", "Date of Entry :"))
        self.SOGM_PI_TEXT.setToolTip(_translate("AppointmentManagement", "<html><head/><body><p><span style=\" font-weight:600;\">Ex.PR00001</span></p></body></html>"))
        self.SOGM_submit_btn.setText(_translate("StockOfGoodsManagement", "Submit"))
        self.SOGM_update_btn.setText(_translate("StockOfGoodsManagement", "Update"))
        self.SOGM_delete_btn.setText(_translate("StockOfGoodsManagement", "Delate"))
        self.SOGM_view_btn.setText(_translate("StockOfGoodsManagement", "View"))
        self.menuOption.setTitle(_translate("StockOfGoodsManagement", "Option"))
        self.menuHelp.setTitle(_translate("StockOfGoodsManagement", "Help"))
        self.actionExit.setText(_translate("StockOfGoodsManagement", "Exit"))
        self.actionAbout.setText(_translate("StockOfGoodsManagement", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StockOfGoodsManagement = QtWidgets.QMainWindow()
    ui = Ui_StockOfGoodsManagement()
    ui.setupUi(StockOfGoodsManagement)
    StockOfGoodsManagement.show()
    sys.exit(app.exec_())
