# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockOfGoodsDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import images.HMS
from About import Ui_AboutWindow
from pymongo import MongoClient

class AlignDelegate(QtWidgets.QStyledItemDelegate):
    def initStyleOption(self, option, index):
        super(AlignDelegate, self).initStyleOption(option, index)
        option.displayAlignment = QtCore.Qt.AlignCenter
        
class Ui_StockOfGoodsDatabase(object):
    def openAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def ShowDatabase(self):
        client = MongoClient('localhost:27017')
        db = client.HSMD
        col = db.SOG_DB
        print("database connected")

        datas = list(col.find({},{"_id": 0,"ID": 1,"SUPPLIER": 1,"PRODUCT NAME": 1,"PRODUCT PRICE": 1,"STOCK": 1,"PACKAGING DATE": 1,"DATE OF ENTRY": 1}))
        self.tableWidget.setRowCount(21)
        delegate = AlignDelegate(self.tableWidget)
        self.tableWidget.setItemDelegate(delegate)

        # print pada tabel
        keys = datas[0].keys()
        for index, key in enumerate(keys):
            # print(type(key), key)
            self.tableWidget.setItem(
                0, index, QtWidgets.QTableWidgetItem(key))

        # print data dke tabel
        for row_index, data in enumerate(datas):
            for col_index, key in enumerate(data.keys()):
                # tambah 1 karena tambah pala
                self.tableWidget.setItem(
                    row_index , col_index,  QtWidgets.QTableWidgetItem(str(data[key])))
                

    def setupUi(self, StockOfGoodsDatabase):
        StockOfGoodsDatabase.setObjectName("StockOfGoodsDatabase")
        StockOfGoodsDatabase.setWindowModality(QtCore.Qt.NonModal)
        StockOfGoodsDatabase.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix4/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StockOfGoodsDatabase.setWindowIcon(icon)
        StockOfGoodsDatabase.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(StockOfGoodsDatabase)
        self.centralwidget.setObjectName("centralwidget")

        self.SOGD_LD_btn = QtWidgets.QPushButton(self.centralwidget)
        self.SOGD_LD_btn.setGeometry(QtCore.QRect(1010, 760, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SOGD_LD_btn.setFont(font)
        self.SOGD_LD_btn.setStyleSheet("color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.857143, y2:0.857955, stop:0 rgba(112, 161, 255,1.0), stop:1 rgba(55, 66, 250,1.0));\n"
"    border-radius: 20px;")
        self.SOGD_LD_btn.clicked.connect(self.ShowDatabase)
        self.SOGD_LD_btn.setObjectName("SOGD_LD_btn")

        self.SOGD_back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.SOGD_back_btn.setGeometry(QtCore.QRect(1400, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SOGD_back_btn.setFont(font)
        self.SOGD_back_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(58, 68, 255);\n"
"border-radius: 20px;")
        self.SOGD_back_btn.clicked.connect(StockOfGoodsDatabase.close)
        self.SOGD_back_btn.setObjectName("SOGD_back_btn")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1601, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(58, 68, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 150, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: rgb(58, 134, 255);\n"
"    background-color: white;\n"
"    border: 2px solid rgb(58, 134, 255);\n"
"    border-radius: 20px;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(600, 150, 971, 571))
        self.tableWidget.setStyleSheet("selection-background-color: qlineargradient(x1: 0, y1: 0, x2: 0.5, y2: 0.5,\n"
"                                stop: 0 #25CCF7, stop: 1 #1B9CFC);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.verticalHeader().setDefaultSectionSize(38)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 80, 561, 791))
        self.label_3.setStyleSheet("image: url(:/newPrefix5/database4.png);\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 81, 81))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"image: url(:/newPrefix4/icon.png);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3.raise_()
        self.label.raise_()
        self.SOGD_LD_btn.raise_()
        self.SOGD_back_btn.raise_()
        self.label_4.raise_()
        self.tableWidget.raise_()
        self.label_2.raise_()
        StockOfGoodsDatabase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StockOfGoodsDatabase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        StockOfGoodsDatabase.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(StockOfGoodsDatabase)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(StockOfGoodsDatabase)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOption.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(StockOfGoodsDatabase)
        QtCore.QMetaObject.connectSlotsByName(StockOfGoodsDatabase)

        self.actionAbout.triggered.connect(self.openAbout)
        self.actionExit.triggered.connect(StockOfGoodsDatabase.close)

    def retranslateUi(self, StockOfGoodsDatabase):
        _translate = QtCore.QCoreApplication.translate
        StockOfGoodsDatabase.setWindowTitle(_translate("StockOfGoodsDatabase", "HMS - Stock of Goods Management"))
        self.SOGD_LD_btn.setText(_translate("StockOfGoodsDatabase", "Load Data"))
        self.SOGD_back_btn.setText(_translate("StockOfGoodsDatabase", "Back"))
        self.label.setText(_translate("StockOfGoodsDatabase", "                   Stock Of Goods Database"))
        self.label_4.setText(_translate("StockOfGoodsDatabase", "Products Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("StockOfGoodsDatabase", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("StockOfGoodsDatabase", "Supplier"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("StockOfGoodsDatabase", "Product Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("StockOfGoodsDatabase", "Product Price"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("StockOfGoodsDatabase", "Stock Available"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("StockOfGoodsDatabase", "Packaging Date"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("StockOfGoodsDatabase", "Date Of Entry"))
        self.menuOption.setTitle(_translate("StockOfGoodsDatabase", "Option"))
        self.menuHelp.setTitle(_translate("StockOfGoodsDatabase", "Help"))
        self.actionExit.setText(_translate("StockOfGoodsDatabase", "Exit"))
        self.actionAbout.setText(_translate("StockOfGoodsDatabase", "About"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StockOfGoodsDatabase = QtWidgets.QMainWindow()
    ui = Ui_StockOfGoodsDatabase()
    ui.setupUi(StockOfGoodsDatabase)
    StockOfGoodsDatabase.show()
    sys.exit(app.exec_())
